# Generated by Django 4.0.6 on 2022-08-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_datecompleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='dateCompleted',
        ),
    ]
